### ISSUE TITLE
--camel-k flags don't work

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/fuse-online-install#121]
I think there are several issues at play here:

- [x] camel-k images reside under `fuse-tech-preview`, but the scripts refer to `fuse7`
- [x] pulling from `registry.access.redhat.com` as suggested in [1] doesn't work, however pulling form `registry.redhat.io` does, hence this repository should be used (http proxy issues)?
- [x] with all the above fixed, `bash install_ocp.sh --camel-k' installs camel-k, but but not syndesis (could be an issue with my minishift)

[1] https://access.redhat.com/containers/?tab=images#/registry.access.redhat.com/fuse7-tech-preview/fuse-camel-k

**Comment by heiko-braun** [comment]
I think there are several issues at play here:

[ ] camel-k images reside under `fuse-tech-preview`, but the scripts refer to `fuse7`
[ ] pulling from `registry.access.redhat.com` as suggested in [1] doesn't work, however pulling form `registry.redhat.io` does, hence this repository should be used (http proxy issues)?
[ ] with all the above fixed, `bash install_ocp.sh --camel-k' installs camel-k, but but not syndesis

**Comment by heiko-braun** [comment]
@nicolaferraro This might address some of the issues: https://github.com/syndesisio/fuse-online-install/pull/122

**Comment by avano** [comment]
@heiko-braun also I think there should be `registry.redhat.io` for all images - https://github.com/syndesisio/syndesis/issues/4165 , currently all image streams use `registry.access.redhat.com` - https://github.com/syndesisio/fuse-online-install/blob/1.6.17/resources/fuse-online-image-streams.yml

**Comment by avano** [comment]
(basically this :-) https://github.com/syndesisio/fuse-online-install/issues/89)
