### ISSUE TITLE
[clarification] Typo in fuse-online-upgrade image

### ISSUE THREAD

**Issue by JameelB** [syndesisio/fuse-online-install#131]
The fuse-online-upgrade image is defined as `fuse-ignite-uprade` in the pod definition [1]. This image doesn't exist in the registry and doesn't match the image defined in the template [2]. 

Should this be defined as `registry.redhat.io/fuse7/fuse-ignite-upgrade:<tag>` instead? 

[1] https://github.com/syndesisio/fuse-online-install/blob/master/resources/fuse-online-upgrade.yml#L8
[2] https://github.com/syndesisio/fuse-online-install/blob/master/resources/fuse-online-template.yml#L1673

**Comment by heiko-braun** [comment]
@JameelB Does the same issue exist in 1.6.x, i.e. https://github.com/syndesisio/fuse-online-install/tree/1.6.20 ?

**Comment by JameelB** [comment]
@heiko-braun Yes I believe it's the same for 1.6.x as well (i.e. https://github.com/syndesisio/fuse-online-install/blob/1.6.20/resources/fuse-online-upgrade.yml#L8)

**Comment by heiko-braun** [comment]
Thanks @JameelB 

@avano TYou have been heavily involved in testing this, what are yout thoughts?

**Comment by avano** [comment]
@heiko-braun I think that is a left-over from the times when we had only the template and not the operator. Currently the docker image for the upgrade is defined in the operator itself - as the operator creates the pod automatically if the deployed fuse online version is different than the operator version.

The upgrade pod template still can be used to upgrade manually in the scenarios when you don't have the operator

**Comment by phantomjinx** [comment]
Issue has been marked as out-of-date and closed.
If it is really required then please reopen and request with justification accordingly.
