### ISSUE TITLE
[7.3.1] Missing tag to a released version

### ISSUE THREAD

**Issue by avano** [syndesisio/fuse-online-install#134]
last one is 2 days old 1.6.22 https://github.com/syndesisio/fuse-online-install/releases/tag/1.6.22 - we will need a new tag (for example `1.6.23`) with official repositories and `1.6` tag pointing to the `1.6.23`

Duplicate of https://issues.jboss.org/browse/ENTESB-10775

**Comment by heiko-braun** [comment]
We will move `1.6` when going GA. Otherwise it interferes with  exsiting installaton routines (i.e. 1.6.22 references brew).

**Comment by avano** [comment]
@heiko-braun my impression was that it was already released since the images are publicly available in the registries. Also quoting Torsten's mail to pm list: 

> I got an email announcement yesterday already that Fuse 7.3.1 is released (and so should have some customers gotten this news who are subscribed via https://access.redhat.com/solutions/36012) and the binaries are already on the download portal.

**Comment by heiko-braun** [comment]
You are absolutely right :) Adding Van, who will take of of this.

**Comment by heiko-braun** [comment]
The actual work is tracked here: https://issues.jboss.org/browse/ENTESB-10775
