### ISSUE TITLE
[1.7.7] Use fuse7-tech-preview instead of fuse-7-tech-preview

### ISSUE THREAD

**Issue by nicolaferraro** [syndesisio/fuse-online-install#148]
A dash changes everything

**Comment by heiko-braun** [comment]
Might be somehting  I messed up

**Comment by heiko-braun** [comment]
https://github.com/syndesisio/fuse-online-install/pull/139/files#diff-297dd78d7c1007508544b4ae7a0ec792L77

**Comment by nicolaferraro** [comment]
Fixed by #151
