### ISSUE TITLE
[1.7.7] No switch for datavirt install

### ISSUE THREAD

**Issue by avano** [syndesisio/fuse-online-install#150]
install_ocp.sh doesn't have a switch for installing with data virtualization

**Comment by heiko-braun** [comment]
@lgarciaaco AFAIK there is two changes needed:

a) increase the replica count for komodo server
b) change a config map (UI?) to enable the DV UI parts

@rkorytkowski Can provide more details.

**Comment by rkorytkowski** [comment]
@heiko-braun, that's correct, if you want to enable it after installation. For b) in config map in syndesis-ui one needs to change datavirt.enabled to 1.

That said the syndesis install script does have a flag to enable data virtualization during installation (`--datavirt`), see https://github.com/syndesisio/syndesis/blob/master/tools/bin/commands/install#L39

Not sure what's the install_ocp.sh script...

**Comment by heiko-braun** [comment]
@nicolaferraro I think @zregvart added a feature flag for Komodo to the CRD. Do you think this can drive the changes to enable Komodo?

**Comment by nicolaferraro** [comment]
Yes, working on it

**Comment by nicolaferraro** [comment]
Fixed by #151
