### ISSUE TITLE
[CamelK] Camel K uses `fuse7` instead of `fuse7-tech-preview` namespace

### ISSUE THREAD

**Issue by avano** [syndesisio/fuse-online-install#155]
Here:

https://github.com/syndesisio/fuse-online-install/blob/ee8d219e2089e6dd06cd5d0d7d136e5c8bc26431/install_ocp.sh#L673

it should use `$repository_tech_preview`

**Comment by heiko-braun** [comment]
Fixed in `1.7.17`
