### ISSUE TITLE
Unable to install as basic user on OCP 4.X

### ISSUE THREAD

**Issue by avano** [syndesisio/fuse-online-install#161]
```
oc login -u admin -p admin <cluster>

./install_ocp.sh --setup                                                       
Installing Syndesis CRD

./install_ocp.sh --grant developer --cluster
Grant permission to create Syndesis to user developer

oc login -u developer -p developer <cluster>
./install_ocp.sh                            
pull secret 'syndesis-pull-secret' is missing, creating ...
enter username for registry.redhat.io and press [ENTER]: 
avano@redhat.com
enter password for registry.redhat.io and press [ENTER]: 
Ensuring imagestreams in syndesis
Deploying Syndesis operator
ERROR: Cannot create remote resource ./resources/fuse-online-operator.yml
```

The underlying error is:

```
oc create -f resources/fuse-online-operator.yml
Error from server (Forbidden): error when creating "resources/fuse-online-operator.yml": roles.rbac.authorization.k8s.io "syndesis-operator" is forbidden: user "developer" (groups=["system:authenticated:oauth" "system:authenticated"]) is attempting to grant RBAC permissions not currently held:
{APIGroups:["extensions"], Resources:["deployments/rollback"], Verbs:["get" "list" "watch"]}
Error from server (NotFound): error when creating "resources/fuse-online-operator.yml": roles.rbac.authorization.k8s.io "syndesis-operator" not found
```

**Comment by heiko-braun** [comment]
@avano Which tag did you use?

**Comment by avano** [comment]
1.7.17

**Comment by heiko-braun** [comment]
@avano Does it work as expected on 3.11?

**Comment by avano** [comment]
yes, on 3.11 it seems to work ok

**Comment by lgarciaaco** [comment]
I will add the permissions independently of `./install_ocp.sh` targeting 3.11 and not 4.x, @heiko-braun ?

**Comment by nicolaferraro** [comment]
No it's not camel-k related. The standard ocp 3.11 edit clusterrole (from which the permissions have been taken) has ["get" "list" "watch"] on "deployments/rollback", but it has been removed on ocp 4.

We can remove the full entry about deployments/rollback since we don't use it at all. That can be done on master + 1.7.x.

If we don't plan to do another Fuse build, we can also patch fuse-online-install to grant that permission on the install user ("--grant" option).
Do we plan to do another build?

**Comment by heiko-braun** [comment]
@nicolaferraro It's not clear if we rebuild. If it can be solved in fuse-online-install, that might be preferrable.

**Comment by nicolaferraro** [comment]
Ok, let's workaround that on fuse-online-install and I'll fix it completely on syndesis master only.

**Comment by lgarciaaco** [comment]
I find discrepancies in the content of the roles, in the following files:

`fuse-online-install/install_ocp.sh`
`fuse-online-install/templates/fuse-online-operator.yml`
`syndesis/install/generator/05-syndesis-security.yml.mustache`
`syndesis/install/operator/deploy/syndesis-operator.yml`

We have to keep those 5 files always aligned, ideally with rules in the same order so we can spot different in the future.

**Comment by nicolaferraro** [comment]
> Ok, let's workaround that on fuse-online-install and I'll fix it completely on syndesis master only.

Only problem is the eval cluster. If we don't rebuild, we should remove the "deployments/rollback" entry manually from the template we provide to users. Btw, is that template created manually?

**Comment by nicolaferraro** [comment]
Oh, if the eval cluster is not OCP4 that's not an issue...

**Comment by heiko-braun** [comment]
Eval is still on 3.11

**Comment by avano** [comment]
works ok now when cherry-picking the commit to 1.7.17 tag
