### ISSUE TITLE
Postgres updated in RH Catalog

### ISSUE THREAD

**Issue by RHodzelmans** [syndesisio/fuse-online-install#188]
My Fuse Online did not come up after installing it. I noticed the database pod was not starting and when I looked into it the reason was due to a missing image. Went to https://access.redhat.com/containers/ to find out only Postgres 9.6 and 10 are available, while the yaml states 9.5 is required. Updated the config to 9.6 and it worked like a charm.

**Comment by zregvart** [comment]
cc @lgarciaaco @KurtStam
