### ISSUE TITLE
import_images.pl still contains the community version of oauth-proxy

### ISSUE THREAD

**Issue by tplevko** [syndesisio/fuse-online-install#60]
Just noticed, that the import_images.pl script still contains the docker.io/openshift/oauth-proxy:v1.1.0

I suppose that as this should be changed to registry.access.redhat.com/openshift3/oauth-proxy:v3.10.45

**Comment by heiko-braun** [comment]
//cc @rhuss

**Comment by heiko-braun** [comment]
good catch @tplevko
