### ISSUE TITLE
Add installation procedures for Camel-K to `install_ocp.sh`

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/fuse-online-install#68]
As a user I want to be able to install Camel-K along side Fuse Online to be able to leverage it from Fuse Online (separate step)

**Comment by heiko-braun** [comment]
@syndesisio/qe  FYI

**Comment by rhuss** [comment]
Fixed with https://github.com/syndesisio/fuse-online-install/pull/69 being merged.
