### ISSUE TITLE
Operator deployment from 1.6.x fails due to missing changes in resources

### ISSUE THREAD

**Issue by avano** [syndesisio/fuse-online-install#81]
```
bash install_ocp.sh --setup
bash install_ocp.sh
```

```
{"level":"info","ts":1554297516.0242584,"logger":"cmd","msg":"Using template","template":"/conf/syndesis-template.yml"}
{"level":"info","ts":1554297516.024355,"logger":"cmd","msg":"Go Version: go1.10.2"}
{"level":"info","ts":1554297516.0243587,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1554297516.0243912,"logger":"cmd","msg":"Version of operator-sdk: v0.5.0"}
{"level":"info","ts":1554297516.0245988,"logger":"leader","msg":"Trying to become the leader."}
{"level":"error","ts":1554297516.0932744,"logger":"cmd","msg":"","error":"required env POD_NAME not set, please configure downward API","stacktrace":"github.com/syndesisio/syndesis/install/operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/syndesisio/syndesis/install/operator/vendor/github.com/go-logr/zapr/zapr.go:128\nmain.main\n\t/go/src/github.com/syndesisio/syndesis/install/operator/cmd/syndesis-operator/main.go:68\nruntime.main\n\t/opt/rh/go-toolset-7/root/usr/lib/go-toolset-7-golang/src/runtime/proc.go:198"}
```

the resources for the operator need to be updated to latest changes

cc @heiko-braun

**Comment by heiko-braun** [comment]
> the resources for the operator need to be updated to latest changes

Can you expand on this ? What do you think is missing?

@lgarciaaco @astefanutti Can you help with this?

**Comment by heiko-braun** [comment]
@avano WHat was your starting point? Plain 1.6.x or a specific tag?

**Comment by heiko-braun** [comment]
@lgarciaaco @astefanutti @nicolaferraro Can you help with this?

**Comment by astefanutti** [comment]
The operator deployment template misses:

https://github.com/syndesisio/syndesis/blob/9dbdd0eda0efd12b909636843601ef90b7bd4ec7/install/operator/deploy/operator.yaml#L31-L34

**Comment by heiko-braun** [comment]
thanks @astefanutti . I wonder how this file from syndesis master makes it to `fuse-online-install/resources`. Is contained within the operator image? Do we keep a redundant copy in fuse-online-install? @nicolaferraro Do you know this?

**Comment by nicolaferraro** [comment]
@heiko-braun I think that what's extracted from the operator image is the template containing syndesis resources, but not the operator.

I think the operator file is to be updated manually here... Roles also may be not aligned to the required version.

**Comment by avano** [comment]
@heiko-braun just for the record, it was from 1.6.x directly.

afaik what the operator misses is:
1) two new env vars for the operator dc (linked by Antonin)
2) as mentioned by Nicola, some roles changed.

here is the diff between 1.5.9 and 1.6.7 of syndesis/install/operator/deploy/syndesis-operator.yml capturing both points: https://gist.github.com/avano/a5fc58454922add4bfd9f9d772b2de1d

**Comment by heiko-braun** [comment]
@nicolaferraro Thanks for the clarification. Could you provide a PR with the necessary changes?

**Comment by nicolaferraro** [comment]
Yes, of course.
