### ISSUE TITLE
Update scripts to install the productised camel-k version

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/fuse-online-install#86]
Are we referencing the correct camel-k version?

See https://github.com/syndesisio/fuse-online-install/blob/master/install_ocp.sh#L529

Or more generally speaking: Using these scripts (`install_ocp.sh --camel-k`), does it install everyhing we need to run camel-k underneath fuse online?

**Comment by nicolaferraro** [comment]
Don't know about the version, @valdar can help on that. AFAIK Camel K is now [built in the pipeline](https://github.com/jboss-fuse/fuse-jenkins-pipelines/blob/71bdfd738cac3784abadb57c5959d88a874cc029/fuse/7.3/Jenkinsfile#L700) and we should update that version field to whatever is built there.

There is an additional step to do to enable camel k that is:
- adding/changing the value of `controllers->integration` to `camel-k` in the `syndesis-server-config` configmap
- restarting syndesis-server

I don't know if it's better adding a script that does that or documenting it. Long-term I think that camel k should be configurable in the syndesis custom resource and the operator should configure the platform for using the right engine.

**Comment by heiko-braun** [comment]
In CR1 it was this one: `fuse7/fuse-camel-k:fuse-7.3-rhel-7-containers-candidate-81569-20190321124048` (See https://issues.jboss.org/browse/ENTESB-10310)

**Comment by heiko-braun** [comment]
It's even worse: https://github.com/syndesisio/fuse-online-install/blob/master/install_ocp.sh#L602

It seems to pull community bits in fuse-online-install. 

@valdar @nicolaferraro Can you update the scripts to work with prod versions?

**Comment by valdar** [comment]
There are others requirements:

- all the maven artefacts must be reachable to camel-k so probably `--camel-k-options "--repository https://$GA_REPO"` should be used.
- Camel syndesis version catalog must be installed in the cluster, it is published as part of `install` of `integration/runtime-camelk` like:
  - `mvn org.apache.maven.plugins:maven-dependency-plugin:copy -Dartifact=io.syndesis.integration:integration-runtime-camelk:<syndesis_version>:yaml:catalog -DoutputDirectory=./`
  - `oc pally -f ./integration-runtime-camelk-<syndesis_version>-catalog.yaml`

**Comment by valdar** [comment]
@heiko-braun We had a chat with @orpiske and @djcoleman, asked to add `kamel` binary to the productized image so we can use that one, without the need of relaying to the upstream version. We had reviewed the image build script that now should properly generate and include the right version of the catalog sparing the need of installing it from maven (i.e. see the second item on my last comment).

Once the new image is generated and the install script updated to use it, we can have an install run and see if this is fixed.

**Comment by heiko-braun** [comment]
Great, thanks for following up on this. If I understand you correctly, with those changes in place, both the `kamel` binary and the catalog will be delivered by the prod team? How to we get access to those artefacts?

**Comment by valdar** [comment]
That is the expectation. We should grab the image from the registry and use the `kamel` binary from there.

**Comment by heiko-braun** [comment]
The catalog as well?

**Comment by valdar** [comment]
The catalog, if we envision everything correctly should be "backed in to the camel-k operator".

**Comment by valdar** [comment]
@orpiske and @djcoleman given https://github.com/jboss-fuse/camel-k/pull/1 and https://github.com/nicolaferraro/fuse-online-install/commit/5ee832fcfa63d34ee762781278a1f802fe809d5c can you give camel-k image creation another go?

**Comment by orpiske** [comment]
@valdar I think we can. Looking at these patches, it seems to me we will need a new PNC build, right @djcoleman?

**Comment by heiko-braun** [comment]
@valdar Cool, are we all set?

**Comment by valdar** [comment]
@nicolaferraro is doing last tests to check all the flow, but he needs the rebuilt image to actually test all the exact flow of installation...

**Comment by heiko-braun** [comment]
ok, let's leave it open for the time being until @nicolaferraro confirmed that it's working as expected

**Comment by nicolaferraro** [comment]
Yeah, this needs to be backported to 1.6.x and I'm still having some issues. It's still using camel `2.23.1` inside..

**Comment by avano** [comment]
@nicolaferraro 

https://github.com/syndesisio/fuse-online-install/blob/038007a1f7b8d6aefa14ef35293b631e83538a03/install_ocp.sh#L639

just a note, this will parse nothing until you have the image pulled locally

@heiko-braun do we want to require the users to have docker installed? Currently when you run `install_ocp.sh`, the script will pull the camel-k docker image to your pc to copy the kamel binary from it. Can't we release the binary as a separate artifact? :thinking: @orpiske ?

cc @tplevko

**Comment by heiko-braun** [comment]
A dependency on docker should be prevented, but since this is TP I would say it's ok.

**Comment by nicolaferraro** [comment]
Thanks @avano, will fix.
Agree, we need to simplify this a bit in 7.4.

**Comment by mmuzikar** [comment]
I used @avano's [fork](https://github.com/avano/fuse-online-install) and were able to get the camel-k operator running, but I got these errors on the camel-k operator:
```
E0412 12:31:08.876235 1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1alpha1.IntegrationPlatform: v1alpha1.IntegrationPlatformList.Items: []v1alpha1.IntegrationPlatform: v1alpha1.IntegrationPlatform.Spec: v1alpha1.IntegrationPlatformSpec.Build: v1alpha1.IntegrationPlatformBuildSpec.Registry: ReadString: expects " or n, but found {, error found in #10 byte of ...|egistry":{},"reposit|..., bigger context ...|-88f2-52540063a234"},"spec":{"build":{"registry":{},"repositories":["https://origin-repository.jboss| ...
```

**Comment by avano** [comment]
Martin used the branch `test` from my fork where I cherry-picked the two commits from https://github.com/syndesisio/fuse-online-install/pull/95 to `1.6.9` tag

**Comment by orpiske** [comment]
...

> 
> @heiko-braun do we want to require the users to have docker installed? Currently when you run `install_ocp.sh`, the script will pull the camel-k docker image to your pc to copy the kamel binary from it. Can't we release the binary as a separate artifact? thinking @orpiske ?
> 
> cc @tplevko

I don't think we have time for that on this release, @avano. I think we could discuss about that for 7.4, though.

**Comment by nicolaferraro** [comment]
> Martin used the branch `test` from my fork where I cherry-picked the two commits from #95 to `1.6.9` tag

I see, it seems a mismatch between the go struct and the actual resource, but I don't experience it.
Can you check if the image of the camel-k-operator deployment is the one coming from brew and also provide the output of `oc get integrationplatfrom -o yaml`?

**Comment by mmuzikar** [comment]
@avano I just noticed I forgot to checkout the Test branch (which is not working) I was able to get the camel-k operator running on master.

@nicolaferraro > oc get integrationplatfrom -o yaml
```error: the server doesn't have a resource type "integrationplatfrom"```

**Comment by heiko-braun** [comment]
@avano @orpiske @nicolaferraro I have created a separate issue to remove the need to have docker available: https://github.com/syndesisio/fuse-online-install/issues/107 it's scheduled for 7.4

**Comment by nicolaferraro** [comment]
I think this can be closed, as issues related to camel k have been solved.
