### ISSUE TITLE
create_secret_if_not_present in update_ocp.sh does not work

### ISSUE THREAD

**Issue by avano** [syndesisio/fuse-online-install#96]
update_ocp.sh checks if the syndesis-pull-secret should be created, but the check is checking if the tag is equal to `1.6.x`, it should rather check if the tag starts with `1.6` 

https://github.com/syndesisio/fuse-online-install/blob/7f84829fd2cae9138ea2122c16d01035a78bb3d7/update_ocp.sh#L443

https://github.com/syndesisio/fuse-online-install/blob/21e63cc4441d65594b4dce1a32fce579442cab1d/fuse_online_config.sh#L2

**Comment by lgarciaaco** [comment]
@heiko-braun can you review pls? For some reason I can't add merge / ask someone from a review from the PR page
