### ISSUE TITLE
update_ocp.sh should apply the changes done in 7.3

### ISSUE THREAD

**Issue by avano** [syndesisio/fuse-online-install#98]
currently the update_ocp.sh just updates the image streams: https://github.com/syndesisio/fuse-online-install/blob/7f84829fd2cae9138ea2122c16d01035a78bb3d7/update_ocp.sh#L433-L461

however there are necessary changes to roles and deployment config of the operator (summary here: https://github.com/syndesisio/fuse-online-install/pull/84/files) + there is new image stream for postgres exporter (https://github.com/syndesisio/fuse-online-install/pull/88/files) that isn't taken into the account during the upgrade

Currently after the upgrade, the operator doesn't start:

```
syndesis-db-1-dbpvl           1/1       Running            0          31m
syndesis-meta-1-6hl7c         1/1       Running            0          31m
syndesis-oauthproxy-1-vp4dc   1/1       Running            0          31m
syndesis-operator-2-vh578     0/1       CrashLoopBackOff   9          24m
syndesis-prometheus-1-td8md   1/1       Running            0          31m
syndesis-server-1-j8dnz       1/1       Running            0          31m
syndesis-ui-1-nr45k           1/1       Running            0          31m
todo-1-7lvwj                  1/1       Running            0          29m
todo-1-build                  0/1       Completed          0          31m

```

**Comment by heiko-braun** [comment]
@lgarciaaco Can you take care of this?
